name: Discord Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları indir
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: ffmpeg yükle
      run: sudo apt-get install -y ffmpeg

    - name: Botu çalıştır
      run: python bot.py
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
