name: Test FFmpeg

on:
  workflow_dispatch:

jobs:
  install-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Check FFmpeg
        run: ffmpeg -version
